# Generated by Django 3.1.5 on 2023-01-06 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_install_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='edited',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Comment on the essay', null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Picked up feedback'), (1, 'Returned feedback')], default=0)),
                ('edited_by', models.ForeignKey(help_text='The editor that provided feedback', on_delete=django.db.models.deletion.CASCADE, related_name='essays_feedback', to=settings.AUTH_USER_MODEL)),
                ('essay', models.OneToOneField(help_text='The essay on which feedback is given', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='project.essay')),
                ('feedback_request', models.OneToOneField(help_text='The feedback request on which feedback is given', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_request', to='project.feedbackrequest')),
            ],
        ),
    ]
