# Generated by Django 3.1.5 on 2023-01-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20230106_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
